name: Publish latest version
on:
  push:
    branches:
      - develop
jobs:
  test-n-publish:
    name: Test and publish Python 🐍 package 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --tag islasgeci/nerd:latest --tag islasgeci/nerd:${GITHUB_SHA:0:4} .
    - name: Check format
      run: docker run islasgeci make check
    - name: Test
      run: docker run islasgeci make coverage
    - name: Run mutation testing
      run: docker run islasgeci make mutants
    - name: Build demo Docker image
      run: docker build --file Dockerfile.demo --tag=islasgeci/nerd_demo:latest --tag islasgeci/nerd_demo:${GITHUB_SHA:0:4} .
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Push latest Docker image to Docker Hub
      run: docker push islasgeci/nerd:latest
    - name: Push SHA tag to Docker Hub
      run: docker push islasgeci/nerd:${GITHUB_SHA:0:4}
    - name: Push latest demo image to Docker Hub
      run: docker push islasgeci/nerd_demo:latest
    - name: Push demo SHA to Docker Hub
      run: docker push islasgeci/nerd_demo:${GITHUB_SHA:0:4}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
