name: JOSS PDF Generator
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Rename old paper
        run: mv paper.md old_paper.md
      - name: Build old paper PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: old_paper.md
      - name: Generate markdown drafts
        run: docker run --volume $PWD/examples:/workdir --volume $PWD/figures:/workdir/figures islasgeci/nerd_demo:latest jupyter nbconvert /workdir/proceedings.ipynb --to markdown
      - name: Copy references to examples
        run: cp references.bib examples/
      - name: Build proceedings PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: examples/proceedings.md
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: paper
          path: |
            paper.pdf
            examples/paper.pdf
