name: JOSS PDF Generator
on: push


jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@master
        with:
          config_path: .github/config/.spellcheck.yml
          task_name: Markdown
      - name: Build proceedings PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: examples/paper.md
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: paper
          path: examples/paper.pdf
