name: Publish testing version
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  test-n-publish:
    name: Test and publish Python 🐍 package 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --tag islasgeci/nerd:testing --tag islasgeci/nerd:${GITHUB_SHA:0:4} .
    - name: Check format
      run: docker run islasgeci/nerd:testing make check
    - name: Test
      run: docker run islasgeci/nerd:testing make coverage
    - name: Run mutation testing
      run: docker run islasgeci/nerd:testing make mutants
    - name: Build demo Docker image
      run: docker build --file Dockerfile.demo --tag=islasgeci/nerd_demo:testing --tag islasgeci/nerd_demo:${GITHUB_SHA:0:4} .
    - name: Verify the notebooks run
      run: docker run --volume ${PWD}:/workdir islasgeci/nerd_demo:testing tests/test_notebooks.sh
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN_TEST }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
